Repository ausaccessfed/workflows, pull requests merged in 2024-09, with the labels that each got.

#332 Fail finish step when intermediate step cancelled
  .github/workflows/deploy-sync.yml
Labels: bug

#335 Upgrade eslint 9.9.1 -> 9.10.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#339 Upgrade renovatebot/github-action action v40.2.7 -> v40.2.8
  .github/workflows/renovate-dependency-check.yml
Labels: dependencies

#328 Lock file maintenance
  yarn.lock
Labels: dependencies

#326 Upgrade actions/upload-artifact action v4.3.6 -> v4.4.0
  .github/actions/build/action.yaml
  .github/actions/command_runner/action.yaml
Labels: dependencies

#280 Upgrade github-api-signature 1.0.0 -> 1.2.0
  package.json
  yarn.lock
Labels: dependencies

#349 Upgrade eslint 9.10.0 -> 9.11.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#350 Upgrade eslint 9.11.0 -> 9.11.1
  package.json
  yarn.lock
Labels: devDependencies, dependencies
