Repository ausaccessfed/workflows, pull requests merged in 2024-08, with the labels that each got.

#287 Fix missed renames of self-approve-tidying.yml
  .github/workflows/distributions/.github/workflows/self-approve-tidying.yml
  .github/workflows/use-self-approve-tidying.yml
Labels: bug

#288 Upgrade eslint 9.8.0 -> 9.9.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#264 If PR labels are missing, check again
  .github/workflows/pr-housekeeping.yml
Labels: bug

#313 Upgrade eslint 9.9.0 -> 9.9.1
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#324 Fix syntax error in self-approve-tidying.yml
  .github/workflows/self-approve-tidying.yml
Labels: bug

#195 Upgrade renovatebot/github-action action v40.2.0 -> v40.2.7
  .github/workflows/renovate-dependency-check.yml
Labels: dependencies

#249 Upgrade docker/setup-buildx-action action v3.4.0 -> v3.6.1
  .github/actions/build/action.yaml
  .github/actions/publish_manifest/action.yaml
Labels: dependencies

#248 Upgrade docker/login-action action v3.2.0 -> v3.3.0
  .github/actions/init/action.yaml
Labels: dependencies

#235 Upgrade @octokit/rest 21.0.0 -> 21.0.2
  package.json
  yarn.lock
Labels: dependencies

#232 Upgrade docker/build-push-action action v6.3.0 -> v6.7.0
  .github/actions/build/action.yaml
Labels: dependencies

#210 Upgrade actions/setup-node action v4.0.2 -> v4.0.3
  .github/workflows/workflow-distributor.yml
Labels: dependencies

#282 Upgrade actions/upload-artifact action v4.3.4 -> v4.3.6
  .github/actions/build/action.yaml
  .github/actions/command_runner/action.yaml
Labels: dependencies
