Repository ausaccessfed/workflows, pull requests merged in 2024-10, with the labels that each got.

#393 Upgrade eslint-plugin-import 2.30.0 -> 2.31.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#395 Upgrade eslint 9.11.1 -> 9.12.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#399 Upgrade eslint 9.12.0 -> 9.13.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#404 Fix slack webhook location
  .github/workflows/deploy-sync.yml
Labels: technical quality

#408 Fix conditional for initial /deploy slack webhook
  .github/workflows/deploy-sync.yml
Labels: technical quality

#396 Upgrade actions/upload-artifact action v4.4.0 -> v4.4.3
  .github/actions/build/action.yaml
  .github/actions/command_runner/action.yaml
Labels: dependencies

#394 Upgrade actions/cache action v4.0.2 -> v4.1.2
  .github/workflows/backup-repos.yml
Labels: dependencies

#392 Upgrade docker/setup-buildx-action action v3.6.1 -> v3.7.1
  .github/actions/build/action.yaml
  .github/actions/publish_manifest/action.yaml
Labels: dependencies

#348 Upgrade actions/setup-node action v4.0.3 -> v4.1.0
  .github/workflows/workflow-distributor.yml
Labels: dependencies

#388 Upgrade docker/build-push-action action v6.7.0 -> v6.9.0
  .github/actions/build/action.yaml
Labels: dependencies

#365 Upgrade actions/checkout action v4.1.7 -> v4.2.2
  .github/actions/init/action.yaml
  .github/workflows/workflow-distributor.yml
Labels: dependencies

#346 Upgrade renovatebot/github-action action v40.2.8 -> v40.3.4
  .github/workflows/renovate-dependency-check.yml
Labels: dependencies

#343 Lock file maintenance
  yarn.lock
Labels: dependencies

#413 Upgrade eslint-plugin-yml 1.14.0 -> 1.15.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies
