Repository ausaccessfed/workflows, pull requests merged in 2025-03, with the labels that each got.

#459 Upgrade eslint 9.21.0 -> 9.22.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#433 Upgrade actions/cache action v4.1.2 -> v4.2.2
  .github/workflows/backup-repos.yml
Labels: dependencies

#472 Fix dev deploy notification action
  .github/workflows/deploy-sync.yml
Labels: technical quality

#473 Fix dev deploy action runs on
  .github/workflows/deploy-sync.yml
Labels: technical quality

#481 Upgrade eslint 9.22.0 -> 9.23.0
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#487 Fix commit status env var
  .github/workflows/deploy-sync.yml
Labels: bug

#460 Upgrade docker/login-action action v3.3.0 -> v3.4.0
  .github/actions/init/action.yaml
Labels: dependencies

#455 Upgrade Node.js v20.19.0 -> v22.14.0
  .nvmrc
Labels: dependencies

#446 Upgrade actions/setup-node action v4.1.0 -> v4.3.0
  .github/workflows/workflow-distributor.yml
Labels: dependencies

#468 Upgrade actions/cache action v4.2.2 -> v4.2.3
  .github/workflows/backup-repos.yml
Labels: dependencies

#456 Upgrade actions/download-artifact action v4.1.8 -> v4.2.1
  .github/actions/publish_manifest/action.yaml
Labels: dependencies

#443 Upgrade lint
  package.json
  yarn.lock
Labels: devDependencies, dependencies

#448 Upgrade aws-actions/configure-aws-credentials action v4.0.2 -> v4.1.0
  .github/actions/init/action.yaml
Labels: dependencies

#417 Upgrade renovatebot/github-action action v40.3.4 -> v40.3.6
  .github/workflows/renovate-dependency-check.yml
Labels: dependencies

#418 Upgrade renovatebot/github-action action v40.3.4 -> v41.0.17
  .github/workflows/renovate-dependency-check.yml
Labels: dependencies

#425 Upgrade docker/build-push-action action v6.9.0 -> v6.15.0
  .github/actions/build/action.yaml
Labels: dependencies

#439 Upgrade @octokit/rest 21.0.2 -> 21.1.1
  package.json
  yarn.lock
Labels: dependencies

#421 Upgrade xt0rted/pull-request-comment-branch action v2.0.0 -> v3.0.0
  .github/actions/branch_finder/action.yaml
  .github/workflows/deploy-sync.yml
  .github/workflows/self-approve-tidying.yml
Labels: dependencies

#281 Upgrade github-api-signature 1.2.0 -> 2.0.1
  package.json
  yarn.lock
Labels: dependencies

#336 Upgrade diff 5.2.0 -> 7.0.0
  package.json
  yarn.lock
Labels: dependencies

#542 Updating distribution files
  .github/workflows/self-approve-tidying.yml
Labels: workflowDistribution

#549 Updating distribution files
  .github/workflows/todo-processor.yml
Labels: workflowDistribution

#550 Updating distribution files
  .vscode/extensions.json
Labels: workflowDistribution

#551 Updating distribution files
  .github/workflows/pr-housekeeping.yml
Labels: workflowDistribution

#554 Updating distribution files
  .github/workflows/todo-processor.yml
Labels: workflowDistribution
